fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

index:
    path:     /
    defaults: { _controller: "MessengerBundle:Messenger:show" }

user:
    path:     /profile/{id}
    defaults: { _controller: "MessengerBundle:User:profile" }